# Generated by Django 2.2.5 on 2019-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='studentname',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='alldocuments',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Additionalinfo',
            field=models.CharField(max_length=500),
        ),
    ]
